/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.syntouch.duiken

import nl.syntouch.utils.Assert.Companion.assertEquals


fun main() {
    var name:String? = "Kevin"
    assertEquals(5, name?.length ?: throw IllegalArgumentException())
    name = null

    val names:List<String> = listOf("Raymond", "Poedel")

    for (name in names) {
        println(name!!.length)
    }
}
